#!/usr/bin/perl
chdir ("java_code");
if ($ARGV[0] eq "") 
{
	system("java AmaImageParser 1\n");
}
else 
{
if ($ARGV[1] eq "") 
{
	system("java AmaImageParser ".$ARGV[0]."\n");
} 
else 
{
if ($ARGV[2] eq "") 
{
	system("java AmaImageParser ".$ARGV[0]." ".$ARGV[1]."\n");
} 
else 
{
if ($ARGV[3] eq "") 
{
	system("java AmaImageParser ".$ARGV[0]." ".$ARGV[1]."\n");
} 
else 
{
if ($ARGV[4] eq "") 
{
	system("java AmaImageParser ".$ARGV[0]." ".$ARGV[1]." ".$ARGV[2]." ".$ARGV[3]."\n");
} 
else 
{
if ($ARGV[5] eq "") 
{
	system("java AmaImageParser ".$ARGV[0]." ".$ARGV[1]." ".$ARGV[2]." ".$ARGV[3]." ".$ARGV[4]."\n");
} 
else 
{
	system("java AmaImageParser ".$ARGV[0]." ".$ARGV[1]." ".$ARGV[2]." ".$ARGV[3]." ".$ARGV[4]." ".$ARGV[5]."\n");
}
}
}
}
}
}
