name: uflow
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - tensorflow[and-cuda]==2.15.1
      - tensorflow-addons==0.23.0
      - absl-py>=1.4,<3
      - gin-config>=0.5,<1
      - imageio>=2.34,<3
      - matplotlib>=3.8,<4
      - numpy<2
      - opencv-python>=4.8,<5
      - scipy>=1.11,<2
      - six>=1.16,<2
      - tensorboard>=2.15,<3
